-- Seed script: Insert all hardcoded job titles into client_dropdown_options as position_title entries.
-- Run this manually against your Supabase/PostgreSQL database.
-- Each title gets an incrementing display_order for consistent ordering.

INSERT INTO client_dropdown_options (list_type, name, display_order)
VALUES
  ('position_title', '310S Mechanic', 1),
  ('position_title', 'Account Clerk', 2),
  ('position_title', 'Accounting Technician', 3),
  ('position_title', 'Accounts Receivable Specialist', 4),
  ('position_title', 'Admin Assistant', 5),
  ('position_title', 'Admin Coordinator / Support', 6),
  ('position_title', 'Administrative Roles (Various)', 7),
  ('position_title', 'Amazon Delivery Associate', 8),
  ('position_title', 'Analyst (AR/AP, Reporting, QA)', 9),
  ('position_title', 'Assembler', 10),
  ('position_title', 'Auditor', 11),
  ('position_title', 'AV Technician', 12),
  ('position_title', 'AZ Driver', 13),
  ('position_title', 'Bartender', 14),
  ('position_title', 'Basketball Coach/Official', 15),
  ('position_title', 'BBQ Station Attendant', 16),
  ('position_title', 'Bilingual Customer Service Representative', 17),
  ('position_title', 'Billing Clerk', 18),
  ('position_title', 'Blaster', 19),
  ('position_title', 'Blender / Blending Operator', 20),
  ('position_title', 'Blow Mold Operator', 21),
  ('position_title', 'Book Department Associate', 22),
  ('position_title', 'Boom DZ Driver', 23),
  ('position_title', 'Bottle Packer', 24),
  ('position_title', 'Business Analyst', 25),
  ('position_title', 'Cabinet Maker', 26),
  ('position_title', 'Car Cleaner / Shuttler', 27),
  ('position_title', 'Car Wash Attendant', 28),
  ('position_title', 'Cargo Handler', 29),
  ('position_title', 'Chef', 30),
  ('position_title', 'Cherry Picker Operator', 31),
  ('position_title', 'Class 1/3/5 Driver', 32),
  ('position_title', 'Cleaner / Janitor / Housekeeper', 33),
  ('position_title', 'CNC Machinist / Operator', 34),
  ('position_title', 'Counterbalance Operator', 35),
  ('position_title', 'Cuber', 36),
  ('position_title', 'Customer Service Representative (CSR)', 37),
  ('position_title', 'Data Entry Clerk', 38),
  ('position_title', 'Daycab Driver', 39),
  ('position_title', 'Decking Labourer', 40),
  ('position_title', 'Dishwasher', 41),
  ('position_title', 'Dispatch Supervisor / Dispatcher', 42),
  ('position_title', 'Dock Worker / Coordinator / Supervisor', 43),
  ('position_title', 'Draftsman / Estimator', 44),
  ('position_title', 'Driver Coordinator / Helper', 45),
  ('position_title', 'DZ Driver', 46),
  ('position_title', 'Engineer (Admin, Project, Process)', 47),
  ('position_title', 'Equipment Operator (F/L, Machine, Line)', 48),
  ('position_title', 'Feeder / Packer', 49),
  ('position_title', 'Filler Operator', 50),
  ('position_title', 'Fitter / Welder', 51),
  ('position_title', 'Foreman', 52),
  ('position_title', 'Forklift Operator', 53),
  ('position_title', 'Front Desk Manager', 54),
  ('position_title', 'G Class Driver', 55),
  ('position_title', 'Garment Sorter / Hanger / Inspector', 56),
  ('position_title', 'Gear Cutter', 57),
  ('position_title', 'General Helper / Labourer', 58),
  ('position_title', 'GL / Driver Helper', 59),
  ('position_title', 'Handler', 60),
  ('position_title', 'Handyman / Technician', 61),
  ('position_title', 'Health and Safety Manager', 62),
  ('position_title', 'Heavy Lifter / Packer', 63),
  ('position_title', 'HR (Coordinator, Support, Generalist)', 64),
  ('position_title', 'Industrial Painter', 65),
  ('position_title', 'Industrial Sewer', 66),
  ('position_title', 'Inspector / Quality Control', 67),
  ('position_title', 'Inventory Clerk / Specialist / Supervisor', 68),
  ('position_title', 'IT Tech Support', 69),
  ('position_title', 'Kitchen Associate', 70),
  ('position_title', 'Landscape Labourer', 71),
  ('position_title', 'Laser Cutter', 72),
  ('position_title', 'Lead Hand / Team Lead', 73),
  ('position_title', 'Licensed Mechanic (Truck/Coach, Millwright)', 74),
  ('position_title', 'Loader / Unloader', 75),
  ('position_title', 'Logistics Coordinator / Associate', 76),
  ('position_title', 'Low Voltage Technician', 77),
  ('position_title', 'Lumper', 78),
  ('position_title', 'Maintenance (Technician, Helper, Millwright)', 79),
  ('position_title', 'Material Handler', 80),
  ('position_title', 'Mig / TIG Welder', 81),
  ('position_title', 'Office Admin / Clerk / Worker', 82),
  ('position_title', 'Operations Support', 83),
  ('position_title', 'Order Picker / Preparer', 84),
  ('position_title', 'Orientation Facilitator', 85),
  ('position_title', 'Package / Parcel Handler', 86),
  ('position_title', 'Palletizer', 87),
  ('position_title', 'Payroll Administrator', 88),
  ('position_title', 'Permanent Position', 89),
  ('position_title', 'Photographer', 90),
  ('position_title', 'Powder Coater Painter', 91),
  ('position_title', 'Press Operator', 92),
  ('position_title', 'Production Associate (Aftn included)', 93),
  ('position_title', 'PSW (Personal Support Worker)', 94),
  ('position_title', 'Purchasing Coordinator', 95),
  ('position_title', 'QA Associate', 96),
  ('position_title', 'Raymond Reach Operator', 97),
  ('position_title', 'Receiver', 98),
  ('position_title', 'Receptionist', 99),
  ('position_title', 'Reimbursements Clerk', 100),
  ('position_title', 'Reno Run Driver', 101),
  ('position_title', 'Retail Associate / Material Handler', 102),
  ('position_title', 'Room Attendant', 103),
  ('position_title', 'Runner', 104),
  ('position_title', 'Sales Associate / Coordinator', 105),
  ('position_title', 'Sanitation Worker (Light / Heavy)', 106),
  ('position_title', 'Sawyer', 107),
  ('position_title', 'Scanner', 108),
  ('position_title', 'Seamstress', 109),
  ('position_title', 'Security', 110),
  ('position_title', 'Server / Service Agent', 111),
  ('position_title', 'Shipper / Receiver', 112),
  ('position_title', 'Shunt Driver', 113),
  ('position_title', 'Skilled Labourer / Trade', 114),
  ('position_title', 'Sorter', 115),
  ('position_title', 'Stacker Operator', 116),
  ('position_title', 'Stamp Operator', 117),
  ('position_title', 'Standby Worker', 118),
  ('position_title', 'Straight Truck Driver', 119),
  ('position_title', 'Subcontractor', 120),
  ('position_title', 'Supervisor', 121),
  ('position_title', 'Table Head', 122),
  ('position_title', 'TBNS (To Be Named Shift)', 123),
  ('position_title', 'Technician', 124),
  ('position_title', 'Tire Installer', 125),
  ('position_title', 'Training Coordinator', 126),
  ('position_title', 'Transportation Associate', 127),
  ('position_title', 'Walkie Rider Operator', 128),
  ('position_title', 'Warehouse Associate / Manager / Supervisor', 129),
  ('position_title', 'Weld Operator / Welder-Fitter', 130),
  ('position_title', 'Yard Cleaner / Coordinator', 131)
ON CONFLICT DO NOTHING;
