import Handlebars from 'handlebars';

interface InvoiceEmailTemplateVars {
  invoiceNumber: string;
  invoiceDate: string;
  dueDate: string;
  clientName: string;
  clientEmail: string;
  grandTotal: string;
  currency: string;
  messageOnInvoice?: string;
}

const templateSource = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Invoice {{invoiceNumber}}</title>
  <style>
    body { font-family: Arial, sans-serif; background: #f8f8f8; color: #222; }
    .container { background: #fff; max-width: 600px; margin: 32px auto; padding: 32px; border-radius: 8px; box-shadow: 0 2px 8px #eee; }
    .header { border-bottom: 1px solid #eee; margin-bottom: 24px; }
    .header h1 { margin: 0; font-size: 2em; color: #2a4d8f; }
    .info-table { width: 100%; margin-bottom: 24px; }
    .info-table td { padding: 4px 0; }
    .amount { font-size: 1.5em; color: #2a4d8f; font-weight: bold; }
    .footer { margin-top: 32px; font-size: 0.95em; color: #666; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Invoice #{{invoiceNumber}}</h1>
      <p>Issued: <strong>{{invoiceDate}}</strong> &nbsp; | &nbsp; Due: <strong>{{dueDate}}</strong></p>
    </div>
    <table class="info-table">
      <tr>
        <td><strong>Client:</strong></td>
        <td>{{clientName}}</td>
      </tr>
      <tr>
        <td><strong>Email:</strong></td>
        <td>{{clientEmail}}</td>
      </tr>
      <tr>
        <td><strong>Amount Due:</strong></td>
        <td class="amount">$ {{grandTotal}}</td>
      </tr>
    </table>
    {{#if messageOnInvoice}}
      <div class="message">
        <p>{{messageOnInvoice}}</p>
      </div>
    {{/if}}
    <div class="footer">
      <p>This invoice was generated by HD Group Ops Portal.<br>
      Please see the attached PDF for full details.</p>
    </div>
  </div>
</body>
</html>
`;

const compiledTemplate = Handlebars.compile(templateSource);

export function invoiceHtmlTemplate(vars: InvoiceEmailTemplateVars): string {
  return compiledTemplate(vars);
} 